valor1 = float(input("Digite o primeiro valor: "))
valor2 = float(input("Digite o segundo valor: "))
valor3 = float(input("Digite o terceiro valor: "))
maior_valor=max(valor1,valor2,valor3)
print(maior_valor)
